on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Building an deployment
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Building and deployment
      uses: 571530/actions-test@master
      env: 
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: out
        NO_JEKYLL: true
        BUILD_SCRIPT: mkdir out && echo "<html><body>hei2</body></html>" >> out/index.html

