name: Building and deployment
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Building an deployment
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Building and deployment
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: out
        BUILD_SCRIPT: mkdir out && echo "<html><body>halla5</body></html>" >> out/index.html && touch out/.nojekyll

