on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: 571530/actions-test@master
      env: 
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: out
